### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by jack828** [Slash-by-Zero/AoC#1]
Hello!

I am very fond of your testbench file and it's output format.

I'd like to take it for my AOC repo and adjust to suit my needs/structure/etc, however as there is no license file in your repo, nobody can take your code, even with attribution.

Would you be open to adding a license so me and others can use, with attribution?

**Comment by Slash-by-Zero** [comment]
Yep sorry!
Fixed now!

**Comment by jack828** [comment]
Many thanks!
